apiVersion: v2
name: bromo
description: Bromo event pipeline boilerplate (Spring Boot + Kafka + Cassandra + PostgreSQL + Redis)
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - events
  - pipeline
  - cloudevents
  - kafka
home: https://github.com/raihanpka/bromo-event-pipeline
sources:
  - https://github.com/raihanpka/bromo-event-pipeline
maintainers:
  - name: raihanpka
    url: https://github.com/raihanpka
